---
system: osx
os: osx

executables:
  brew: /usr/local/bin/brew
  vim: /usr/bin/vim
  bash: /bin/bash

directories:
  etc: /usr/local/etc
  var: /usr/local/var

me:
  user:
    name: richard
    group: staff
    shell: "{{ executables.bash }}"

  template_home: home/richard
  home: /Users/richard
  system: osx
