---
- name: gitconfigs
  copy:
    src: "{{ item }}"
    dest: "{{ me.home }}/.{{ item }}"
    mode: 0644
  loop:
    - gitconfig
    - gitconfig.reflow

- name: git dir
  file:
    path: "{{ me.home }}/git"
    state: directory
    mode: 0755

- name: git clone loop
  git:
    repo: "git@git.invoice2go.org:ops/{{ item.repo }}.git"
    dest: "{{ me.home }}/git/{{ item.dest }}"
    update: no
  loop:
    - { repo: 'deploy',       dest: 'deploy' }
    - { repo: 'kong',         dest: 'kong' }
    - { repo: 'puppet',       dest: 'puppet' }
    - { repo: 'scripts',      dest: 'scripts' }
    - { repo: 'terraform',    dest: 'terraform' }
    - { repo: 'terrasandbox', dest: 'sandbox' }
