---
- name: tools dirs
  file:
    path: "{{ me.home }}/{{ item }}"
    mode: 0755
    state: directory
  loop:
    - .aws

- name: tools configs
  file:
    dest: "{{ me.home }}/{{ item.d }}"
    src: "{{ item.s }}"
  loop:
    - { s: 'aws.config', d: '.aws/config' }

- name: python pip installed tools
  pip:
    name: "{{ item }}"
  loop:
    - awsume
    - requests

- name: ruby gem installed tools
  gem:
    name: "{{ item }}"
  loop:
    - git_reflow

- name: awsume console plugin
  command: awsume --install-plugin https://raw.githubusercontent.com/trek10inc/awsume/master/examplePlugin/console.py https://raw.githubusercontent.com/trek10inc/awsume/master/examplePlugin/console.yapsy-plugin
  args:
    creates: "{{ me.home }}/.aws/awsumePlugins/console.py"

