---
- name: vim | .vimrc
  copy:
    src: vimrc
    dest: "{{ me.home }}/.vimrc"
    mode: 0644

- name: vim | git clone ultimate vimrc
  git:
    repo: https://github.com/quanghiem/vimrc.git
    dest: "{{ me.home }}/.vim_runtime"

- name: vim | my_configs.vim
  copy:
    src: my_configs.vim
    dest: "{{ me.home }}/.vim_runtime/my_configs.vim"
    mode: 0644
  
- name: mkdir ~/.vim/bundle
  file:
    path: ~/.vim/bundle
    mode: 0755
    state: directory
  
- name: vim bundles..
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ me.home }}/.vim/bundle/{{ item.dest }}"
  loop:
    - { repo: 'rodjek/vim-puppet.git',              dest: 'puppet'}
    - { repo: 'stephpy/vim-yaml.git',               dest: 'yaml'}
    - { repo: 'vim-airline/vim-airline-themes.git', dest: 'airline-themes'}
    - { repo: 'vim-airline/vim-airline.git',        dest: 'airline'}
    - { repo: 'vim-scripts/xoria256.vim.git',       dest: 'xoria256'}
