---
- name: vim dirs
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  loop:
    - "~/.vim/bundle"

- name: vim git
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "{{ me.home }}/{{ item.dest }}"
    update: no
  loop:
    - { repo: 'quanghiem/vimrc.git',                dest: '.vim_runtime'}
    - { repo: 'rodjek/vim-puppet.git',              dest: '.vim/bundle/puppet'}
    - { repo: 'stephpy/vim-yaml.git',               dest: '.vim/bundle/yaml'}
    - { repo: 'vim-airline/vim-airline-themes.git', dest: '.vim/bundle/airline-themes'}
    - { repo: 'vim-airline/vim-airline.git',        dest: '.vim/bundle/airline'}
    - { repo: 'vim-scripts/xoria256.vim.git',       dest: '.vim/bundle/xoria256'}

- name: vim configs
  copy:
    src: "{{ item.s }}"
    dest: "{{ me.home }}/{{ item.d }}"
    mode: 0644
  loop:
    - { s: 'my_configs.vim', d: '.vim_runtime/my_configs.vim' }
    - { s: 'vimrc',          d: '.vimrc' }

